# Generated by Django 5.0.6 on 2024-05-25 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_about_alter_event_speakers'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='speakers',
            field=models.ManyToManyField(blank=True, related_name='events', to='teacher.teacher'),
        ),
    ]
