# Generated by Django 5.0.6 on 2024-05-25 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coures',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
