# Generated by Django 5.0.6 on 2024-05-25 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_remove_coures_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coures',
            name='duration',
            field=models.IntegerField(help_text='Duration in days'),
        ),
    ]
