# Generated by Django 5.0.6 on 2024-05-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_coures_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courselesson',
            name='youtube_url',
            field=models.CharField(max_length=200),
        ),
    ]
