# Generated by Django 5.0.6 on 2024-05-25 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usercourse'),
        ('course', '0002_coures_is_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFinishedCourseLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrolled_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_course', to='accounts.usercourse')),
                ('lessons', models.ManyToManyField(related_name='finished_lessons', to='course.coures')),
            ],
            options={
                'verbose_name': 'User Finished Lesson',
                'verbose_name_plural': 'User Finished Lessons',
            },
        ),
    ]
