# Generated by Django 5.0.6 on 2024-05-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userfinishedcourselesson'),
        ('course', '0005_alter_courselesson_youtube_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfinishedcourselesson',
            name='lessons',
            field=models.ManyToManyField(related_name='finished_lessons', to='course.courselesson'),
        ),
    ]
